<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "meinpflegeberuf"
 * Auto generated by Extension Builder 2017-08-14
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Mein Pflegeberuf Template',
    'description' => 'Template \"Mein Pflegeberuf\"',
    'category' => 'distribution',
    'author' => 'Joe Schäfer',
    'author_email' => 'mail@schaefer-webentwicklung.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0-dev',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'bootstrap_grids' => '',
            'gridelements' => '',
            'mask' => '',
            'powermail' => '',
            'realurl' => '',
//            'realurl_clearcache2'  => '',
            'beuser_fastswitch' => '',
//            'dd_googlesitemap' => '',
            'jh_magnificpopup' => '',
            't3monitoring_client' => '',
            'cs_seo' => '',
            'sourceopt' => '',
            'scriptmerger' => '',
            // Sysextensions
            'opendocs' => '',
            'recycler' => '',
        ],
        'conflicts' => [],
        'suggests' => [
            'rx_unrollsavebuttons' => '',
            'go_maps_ext' => '',
            'frontend_editing' => '',
            'lib_js_lazysizes' => '', // https://github.com/joekolade/lib_js_lazysizes
            'cookieconsent2' => '',
            'fluid-styled-responsive-images' => ''
        ],
    ],
];
